routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductosController;
use App\Http\Controllers\CatalogoFigurasController;
use App\Http\Controllers\CatalogoRopaController;
use App\Http\Controllers\VentasController;
use App\Models\Ventas;
use App\Models\Productos;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $productos=Productos::all()->where('categoria', 'Figura');
    return view('home',compact('productos'));
})->name('home');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {$ventas=Ventas::all();
    return view('dashboard', compact('ventas'));
})->name('dashboard');

Route::view('acerca', 'acerca')->name('acerca');

Route::view('contacto','contac')->name('contac');

Route::view('prueba','prueba')->name('prueba');

/*Route::view('contacto', function () { $ventas2=Ventas::all();
    return view('ventas', compact('ventas2'));
})->name('dashboard');*/
Route::resource('catalogoF', CatalogoFigurasController::class);
Route::resource('catalogoR', CatalogoRopaController::class);
Route::resource('ventas', VentasController::class);
Route::middleware(['auth:sanctum', 'verified' , 'authadmin'])->resource('productos', ProductosController::class);

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/agregar_producto.blade.php
<x-app-layout>



    @section('Titulo')
Artisen
@endsection





@section('contenido')


<div class="row justify-content-md-center">
    <div class="col-lg-5 d-flex justify-content-center ">
        <div class="px-lg-5 py-lg-4 p-4 align-self-center w-100">
        <h1 class="d-flex justify-content-center ">Registro Productos</h1>

<form class="mb-3" action="{{ route('productos.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label font-weight-bold">Nombre</label>    
    <input type="text" class="form-control bg-dark-x border-0" name="nombre" placeholder="Ingrese su producto" required/>
    </div>

    <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label font-weight-bold">Descripcion</label>    
    <input type="text" class="form-control bg-dark-x border-0" name="descripcion" placeholder="Ingrese descripcion" value="{{ old('descripcion') }}" required/>
    </div>

    <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label font-weight-bold">Categoria</label>        
    <input type="text" class="form-control bg-dark-x border-0" name="categoria" placeholder="Ingrese categoria" value="{{ old('categoria') }}" required/>
    </div>

    <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label font-weight-bold">Precio</label>   
    <input type="number" class="form-control bg-dark-x border-0" name="precio" placeholder="Ingrese el precio" value="{{ old('precio') }}" required/>
    </div>


    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label font-weight-bold">Cantidad</label>   
        <input type="number" class="form-control bg-dark-x border-0" name="cantidad" placeholder="Ingrese cantidad" value="{{ old('cantidad') }}" required/>
        </div>

    <div class="mb-3">
        <label for="formFile" class="form-label">Ingrese su foto</label>
        <input class="form-control" type="file" name="imagen" required>
        </div>

    <div class="d-flex justify-content-center">
    <button type="submit" class="btn btn-primary w-100 ">Enviar</button>
</div>
</form>


</div>

</div>
</div>
@endsection

</x-app-layout>

resources/views/catalogoF.blade.php
<x-app-layout>
    @section('Titulo')
Artisen
@endsection





@section('contenido')
<div class="bg-dark p-3 mt-4"> 
<h1 class="text-center m-0 text-light">Figuras Anime</h1>
</div>
   



<!-- START SECTION STORE -->
<section class="store mt-5">
  <div class="container">
      <div class="items">
          <div class="row g-2 d-flex justify-content-center">

            
              @foreach ($productos as $productos)
              
              
                  

              <div class="card h-100 d-inline d-flex justify-content-center m-2" style="width: 16rem;" >
                <div class="item shadow">
                  <img src="{{asset('storage/'.$productos->imagen)}}" class="item-image " alt="..." width="250px" height="250px" >
                  <div class="card-body ">
                    <h5 style="display: none;"class="item-id text-center">{{$productos->id}} </h5>
                    <h5 class="item-title text-center">{{$productos->nombre}} </h5>
                    <h5 class="item-price text-center">${{$productos->precio}} </h5>
                    <p class="card-text">{{$productos->descripcion}}</p>


                    @if (Route::has('login'))
                    @auth
                    <button class="item-button btn btn-primary addToCart w-100">AÑADIR AL CARRITO</button>
                      @else
                        <a href="{{ route('login') }}" class="item-button btn btn-primary addToCart w-100">AÑADIR AL CARRITO</a>
                    @endauth
                    @endif
                    

                  </div>
                </div>
                </div>
                  
              @endforeach
                  

            


          </div>
      </div>
  </div>
</section>
<!-- END SECTION STORE -->
<!-- START SECTION SHOPPING CART -->
<section class="shopping-cart">
  <div class="container">
      <h1 class="text-center">CARRITO</h1>
      <hr>
      <div class="row">
          <div class="col-6 ">
              <div class="shopping-cart-header w-100">
                  <h6>Producto</h6>
              </div>
          </div>
          <div class="col-3">
              <div class="shopping-cart-header w-100">
                  <h6 class="text-truncate">Precio</h6>
              </div>
          </div>
          <div class="col-3">
              <div class="shopping-cart-header">
                  <h6>Cantidad</h6>
              </div>
          </div>
      </div>
      <!-- ? START SHOPPING CART ITEMS -->
      <div class="shopping-cart-items shoppingCartItemsContainer">
      </div>
      <!-- ? END SHOPPING CART ITEMS -->

      <!-- START TOTAL -->
      <div class="row">
          <div class="col-12">
              <div class="shopping-cart-total d-flex align-items-center">
                  <p class="mb-0">Total</p>
                  <p class="ml-4 mb-0 shoppingCartTotal">$0</p>
                  <div class="toast ml-auto bg-info" role="alert" aria-live="assertive" aria-atomic="true"
                      data-delay="2000">
                      <div class="toast-header">
                          <span>✅</span>
                          <strong class="mr-auto ml-1 text-secondary">Elemento en el carrito</strong>
                          <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                          </button>
                      </div>
                      <div class="toast-body text-white">
                          Se aumentó correctamente la cantidad
                      </div>
                  </div>

                  
                  <form  action="{{ route('catalogoF.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" id='foo0' name="nom" value=""/>
                    <input type="hidden" id='foo1' name="cant" value=""/>
                    <input type="hidden"  id='foo' name="cost" value=""/>
                    @if (Route::has('login'))
                    @auth
                    
                    <input type="hidden" name="idcli" value={{Auth::user()->id}}>
                    <input type="hidden" name="name" value={{Auth::user()->name}}>
                    @endauth
                    @endif
                    <input type="hidden" id='foo3'name="idpro" value=''>

                    @if (Route::has('login'))
                    @auth
                    <button class="btn btn-success ml-auto comprarButton" type="submit" data-toggle="modal"

                      data-target="#comprarModal">Comprar</button>
                      @else
                        <a href="{{ route('login') }}" class="btn btn-success ml-auto">Comprar</a>
                    @endauth
                    @endif
                    </form>


              </div>
          </div>
      </div>

      <!-- END TOTAL -->

      <!-- START MODAL COMPRA -->
      <div class="modal fade" id="comprarModal" tabindex="-1" aria-labelledby="comprarModalLabel"
          aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                  <div class="modal-header">
                      <h5 class="modal-title" id="comprarModalLabel">Gracias por su compra</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                      </button>
                  </div>
                  <div class="modal-body">
                      <p>Pronto recibirá su pedido</p>
                  </div>
                  <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                  </div>
              </div>
          </div>
      </div>
      <!-- END MODAL COMPRA -->


  </div>

</section>
<!-- END SECTION SHOPPING CART -->


<!-- START FOOTER -->
<footer class="bg-dark p-3 mt-5">
  <p class="text-center m-0 text-muted">Artisen</p>
</footer>
<!-- END FOOTER -->




<!-- SCRIPTS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
  integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
  crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
  integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
  crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
  integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
  crossorigin="anonymous"></script>

<script src="{{('js/tienda.js') }}"></script>






@endsection
       
</x-app-layout>

resources/views/catalogoR.blade.php
<x-app-layout>
    @section('Titulo')
Artisen
@endsection





@section('contenido')
<div class="bg-dark p-3 mt-4"> 
<h1 class="text-center m-0 text-light">Ropa Anime</h1>
</div>
   



<!-- START SECTION STORE -->
<section class="store mt-5">
  <div class="container">
      <div class="items">
          <div class="row g-2 d-flex justify-content-center">

            
              @foreach ($productos as $productos)
              
              
                  

              <div class="card h-100 d-inline d-flex justify-content-center m-2" style="width: 16rem;" >
                <div class="item shadow">
                  <img src="{{asset('storage/'.$productos->imagen)}}" class="item-image  " alt="..." width="250px" height="250px" >
                  <div class="card-body ">
                    <h5 style="display: none;"class="item-id text-center">{{$productos->id}} </h5>
                    <h5 class="item-title text-center">{{$productos->nombre}} </h5>
                    <h5 class="item-price text-center">${{$productos->precio}} </h5>
                    <p class="card-text">{{$productos->descripcion}}</p>
                    @if (Route::has('login'))
                    @auth
                    <button class="item-button btn btn-primary addToCart w-100">AÑADIR AL CARRITO</button>
                      @else
                        <a href="{{ route('login') }}" class="item-button btn btn-primary addToCart w-100">AÑADIR AL CARRITO</a>
                    @endauth
                    @endif
                  </div>
                </div>
                </div>
                  
              @endforeach
                  

            


          </div>
      </div>
  </div>
</section>
<!-- END SECTION STORE -->
<!-- START SECTION SHOPPING CART -->
<section class="shopping-cart">
  <div class="container">
      <h1 class="text-center">CARRITO</h1>
      <hr>
      <div class="row">
          <div class="col-6 ">
              <div class="shopping-cart-header w-100">
                  <h6>Producto</h6>
              </div>
          </div>
          <div class="col-3">
              <div class="shopping-cart-header w-100">
                  <h6 class="text-truncate">Precio</h6>
              </div>
          </div>
          <div class="col-3">
              <div class="shopping-cart-header">
                  <h6>Cantidad</h6>
              </div>
          </div>
      </div>
      <!-- ? START SHOPPING CART ITEMS -->
      <div class="shopping-cart-items shoppingCartItemsContainer">
      </div>
      <!-- ? END SHOPPING CART ITEMS -->

      <!-- START TOTAL -->
      <div class="row">
          <div class="col-12">
              <div class="shopping-cart-total d-flex align-items-center">
                  <p class="mb-0">Total</p>
                  <p class="ml-4 mb-0 shoppingCartTotal">$0</p>
                  <div class="toast ml-auto bg-info" role="alert" aria-live="assertive" aria-atomic="true"
                      data-delay="2000">
                      <div class="toast-header">
                          <span>✅</span>
                          <strong class="mr-auto ml-1 text-secondary">Elemento en el carrito</strong>
                          <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                          </button>
                      </div>
                      <div class="toast-body text-white">
                          Se aumentó correctamente la cantidad
                      </div>
                  </div>

                  
                  <form  action="{{ route('catalogoR.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <input type="hidden" id='foo0' name="nom" value=""/>
                    <input type="hidden" id='foo1' name="cant" value=""/>
                    <input type="hidden"  id='foo' name="cost" value=""/>
                    @if (Route::has('login'))
                    @auth
                    
                    <input type="hidden" name="idcli" value={{Auth::user()->id}}>
                    <input type="hidden" name="name" value={{Auth::user()->name}}>
                    @endauth
                    @endif
                    <input type="hidden" id='foo3'name="idpro" value=''>

                    @if (Route::has('login'))
                    @auth
                    <button class="btn btn-success ml-auto comprarButton" type="submit" data-toggle="modal"

                      data-target="#comprarModal">Comprar</button>
                      @else
                        <a href="{{ route('login') }}" class="btn btn-success ml-auto">Comprar</a>
                    @endauth
                    @endif
                    </form>


              </div>
          </div>
      </div>

      <!-- END TOTAL -->

      <!-- START MODAL COMPRA -->
      <div class="modal fade" id="comprarModal" tabindex="-1" aria-labelledby="comprarModalLabel"
          aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                  <div class="modal-header">
                      <h5 class="modal-title" id="comprarModalLabel">Gracias por su compra</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                      </button>
                  </div>
                  <div class="modal-body">
                      <p>Pronto recibirá su pedido</p>
                  </div>
                  <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                  </div>
              </div>
          </div>
      </div>
      <!-- END MODAL COMPRA -->


  </div>

</section>
<!-- END SECTION SHOPPING CART -->


<!-- START FOOTER -->
<footer class="bg-dark p-3 mt-5">
  <p class="text-center m-0 text-muted">Artisen</p>
</footer>
<!-- END FOOTER -->




<!-- SCRIPTS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
  integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
  crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
  integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
  crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
  integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
  crossorigin="anonymous"></script>

<script src="{{('js/tienda.js') }}"></script>






@endsection
       
</x-app-layout>

resources/views/detalle_producto.blade.php
<x-app-layout>



    @section('Titulo')
Artisen
@endsection





@section('contenido')

<!-- Header -->
<div class="bg-dark p-3 mt-4"> 
  <h1 class="text-center m-0 text-light">Detalles</h1>
  </div>

  <!-- Photo Grid -->
      <!-- Row 1 -->
  <div class="card-deck mt-5">
      <div class="card mb-12">

        <div class="row g-0">

        <div class="col-md-4 d-flex justify-content-center">
        <img src="{{asset('storage/'.$producto->imagen)}}" class="ms-auto m-1" width="100%">
        </div>

        <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">DETALLES</h5>
          <ul class="list-group ">
            <li class="list-group-item list-group-item"><i class="fas fa-id-badge" style="font-size:20px;"></i> ID: {{ $producto->id}}</li>
            <li class="list-group-item list-group-item"><i class="fas fa-shopping-bag" style="font-size:20px;"></i> Producto: {{ $producto->nombre}}</li>
            <li class="list-group-item list-group-item"><i class="fas fa-id-card"style="font-size:20px;"></i> Descripcion: {{ $producto->descripcion}}</li>
            <li class="list-group-item list-group-item"><i class="fas fa-money-bill-alt"style="font-size:20px;"></i> Costo: ${{ $producto->precio}}</li>
            <li class="list-group-item list-group-item"><i class="fas fa-box"style="font-size:20px;"></i> Cantidad: {{$producto->cantidad}}</li>
          </ul>
          
        </div>
    
        <div class="card-footer">
          
          <a href="{{ route('productos.edit', $producto->id)}}" class="btn  btn-warning w-100"><i class="far fa-edit"></i></a>
        </div>
      </div>
      
      </div>
      </div>
  </div>
@endsection

</x-app-layout>

resources/views/editar_producto.blade.php
<x-app-layout>
    @section('Titulo')
Artisen
@endsection





@section('contenido')

<div class="container1 mt-1" >
<form action="{{ route('productos.update', $producto->id) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <h1 id="titulazo">Editar Producto</h1>

    
        <div class="input-group mb-3">
            <div class="titulo1">
            <p>Nombre del articulo</p>
            </div>
        <input type="text" aria-label="First name" class="form-control" name="nombre" value="{{ $producto->nombre}}" required>
        </div>
      


      
      <div class="input-group mb-3">
        <div class="titulo1">
            <p>Descripcion</p>
        </div>
        <textarea class="form-control" aria-label="With textarea" name="descripcion" required>{{$producto->descripcion}}</textarea>
      </div>
    

        <div class="input-group mb-3">
            <div class="titulo1">
                <p>Categoria</p>
                </div>
            <select class="form-select" id="inputGroupSelect01" name="categoria" required>
              <option selected>Ninguna</option>
              <option value="Ropa">Ropa</option>
              <option value="Figura">Figura</option>
            </select>
          </div>

          <div class="container-otro">
            <div class="row align-items-start">
              <div class="col">
                <div class="input-group mb-3">
                    <div class="titulo1">
                    <p>Precio</p>
                    </div>
                    <span class="input-group-text">$</span>
                    <input type="text" class="form-control" aria-label="Amount (to the nearest dollar)" name="precio" value="{{ $producto->precio}}" required>
                    <span class="input-group-text">.00</span>
                </div>
              </div>
              <div class="col">
                <div class="input-group mb-3">
                    <div class="titulo1">
                    <p>Cantidad</p>
                    </div>
                <input type="text" aria-label="First name" class="form-control" name="cantidad" value="{{ $producto->cantidad}}" required>
                <span class="input-group-text">Unidades</span>
                </div>
              </div>
            </div>
          </div>

            <div class="input-group mb-3">
                <div class="titulo1">
                <p>Foto del Producto</p>
                </div>
                <input type="file" class="form-control" id="inputGroupFile04" 
                aria-describedby="inputGroupFileAddon04" aria-label="Upload" name="imagen" value="{{ $producto->imagen}}" required>
            </div>

            <div class="input-group mb-3">
                <button type="submit" id="guardarboton">Guardar</button>
            </div>
      

</div>
</form>


@endsection
       
</x-app-layout>

resources/views/home.blade.php
<x-app-layout>

@section('Titulo')
Artisen
@endsection





@section('contenido')

<!-- inicia carusel -->

<div class="row g-0 mt-4">
  <div class="col-lg-12 d-block">
  <div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">

    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active" data-bs-interval="10000">

        <div id="imagen">
        <img src="{{asset('adjuntos/banner1def.jpg')}}" class="d-block w-100 " alt="..." height="525px">
      </div>

        <div id="h33" class="carousel-caption d-block">
          <h3>Descuentos de Ropa</h3>
          <p>Las mejor ropa la mas perrona solo en Artisen.</p>
        </div>
      </div>
      <div class="carousel-item" data-bs-interval="2000">
        <img src="{{asset('adjuntos/banner2.jpg')}}" class="d-block w-100" alt="..."  height="525px">
        <div id="h33" class="carousel-caption d-block ">
          <h3>Increibles Descuentos de Ropa</h3>
          <p>¿Quieres ser cool? Compra en Artisen.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{{asset('adjuntos/banner3.jpg')}}" class="d-block w-100" alt="..." height="525px">
        <div id="h33" class="carousel-caption d-block">
          <h3>Artisen nya</h3>
          <p>¿Eres bobo? Compra en Artisen Baka.</p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark"  data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Anterior</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark"  data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Siguiente</span>
    </button>
  </div>
  </div>
</div>
  


<div class="bg-dark p-2 mt-5"> 
  <h1 class="text-center m-0 text-light">Los más vendidos de Artisen</h1>
  </div>
<section class="store mt-5">
  <div class="container">
      <div class="items">
          <div class="row g-2 d-flex justify-content-center">
@php
$i = 0
@endphp
@foreach ($productos as $productos)   

@if ($i < 4)

    
<div class="card h-100 d-inline d-flex justify-content-center m-2" style="width: 16rem;" >
  <div class="item shadow">
    <img src="{{asset('storage/'.$productos->imagen)}}" class="item-image  " alt="..." width="250px" height="250px" >
    <div class="card-body ">
      <h5 style="display: none;"class="item-id text-center">{{$productos->id}} </h5>
      <h5 class="item-title text-center">{{$productos->nombre}} </h5>
      <h5 class="item-price text-center">${{$productos->precio}} </h5>
      <p class="card-text">{{$productos->descripcion}}</p>
      @if (Route::has('login'))
      @auth
      <a href="{{ route('catalogoF.index') }}" class="item-button btn btn-primary addToCart w-100">VER EN CATALOGO</a>
        @else
          <a href="{{ route('login') }}" class="item-button btn btn-primary addToCart w-100">VER EN CATALOGO</a>
      @endauth
      @endif
    </div>
  </div>
  </div>
  @php
     $i=$i+1
  @endphp

  @endif
@endforeach


</div>
</div>
</div>
</section>


@endsection

</x-app-layout>

resources/views/lista_productos.blade.php
<x-app-layout>



    @section('Titulo')
Artisen
@endsection





@section('contenido')

<div class="bg-dark p-3 mt-4"> 
    <h1 class="text-center m-0 text-light">Lista de Productos</h1>
    </div>






    <a href="{{route('productos.create')}}" class="btn btn-success w-100 mt-5" >Agregar</a>

    @if(session()->has('mensaje'))
    <p style="color: rgb(14, 182, 56)">{{ session('mensaje') }}</p>
    @endif





    
    <table class="table  mt-2" id="data" class="display">
        <thead class="table-dark">
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Nombre</th>
              <th scope="col">Descripcion</th>
              <th scope="col">Categoria</th>
              <th scope="col">Precio</th>
              <th scope="col">Cantidad</th>
              <th scope="col">Foto</th>

              
              <th scope="col" class="text-center">Opciones</th>
              
            </tr>
          </thead>



        @foreach ($productos as $productos)
        <tbody>    
            <tr>
                <th scope="row">{{ $productos->id }}</th>


                <td>{{ $productos->nombre }}</td>
                <td>{{ $productos->descripcion }}</td>
                <td>{{ $productos->categoria }}</td>
                <td>{{ $productos->precio }}</td>
                <td>{{ $productos->cantidad }}</td>
                <td><img src="{{asset('storage/'.$productos->imagen)}}" 
                     alt="..." width="50px" height="50px"></td>
                
                    

                <td>
                    <div class="d-flex justify-content-center">
                <a href="{{ route('productos.show', $productos->id)}}" class="btn  btn-info active mx-1 d-inline "><i class="far fa-eye"></i></a>
                <a href="{{ route('productos.edit', $productos->id)}}" class="btn  btn-warning active mx-1 d-inline"><i class="far fa-edit"></i></a>
                
                    <form action="{{ route('productos.destroy', $productos->id) }}" method="post" class="d-inline mx-1">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger "><i class="fas fa-trash-alt"></i></button>
                    </form>
                    </div>
                </td>
            </tr>
        @endforeach
    </table>
 

    
    

@endsection

</x-app-layout>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/user.blade.php
<x-app-layout>
    @section('Titulo')
Artisen
@endsection

@section('estilo')
<link rel="stylesheet" href="{{ mix('css/app.css') }}">
@endsection



@section('contenido')

<main>
    {{ $slot }}
</main>
</div>
@stack('modals')
@livewireScripts

@endsection








            
</x-app-layout>